services:

  postgresdb:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_USER: $DATASOURCE_USER
      POSTGRES_PASSWORD: $DATASOURCE_PASSWORD
      POSTGRES_DB: $DATASOURCE_DB
    ports:
      - 5432:5432
